apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: stage-application-pvt
  namespace: argocd

spec:
  project: default

  destination:
    namespace: stage
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/markokli/devops-ex-svs
    targetRevision: HEAD
    path: cluster/overlays/stage

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
        #automated:
        #  prune: true
        #  selfHeal: false
