apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
  environment: test-stage

namePrefix: test-stage-

namespace: test-stage

patches:
- target:
    kind: Service
    labelSelector: "application=app2"
    version: v1
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30100
