apiVersion: v1
kind: Service

metadata:
  name: app1-svc
  labels: 
    application: app1
    
spec:
  type: NodePort

  selector:
    application: app1

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
