apiVersion: v1
kind: Service

metadata:
  name: app2-svc
  labels: 
    application: app2
    
spec:
  type: NodePort

  selector:
    application: app2

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30200
