name: ci-app1

on:
  push:
    branches:
      - 'main'
      - 'klincharov'
    paths:
      - 'apps/app1/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        #-
        #  Get the current SemVer tag from dockerhub
        #  name: Get Docker image SemVer tag
        #  uses: docker/metadata-action@v4
        #  id: docker-semver-extract
        #  with:
        #    images: name/markoklin/practice-repo #aandonov/app1:latest
        #    tags: type=semver,pattern={{ version }}
      
      - 
        name: Build and push app1
        uses: docker/build-push-action@v3
        with:
          context: apps/app1/.
          push: true
          tags: markoklin/practice-repo #aandonov/app1:stage-v${{ MAJOR }}.${{ MINOR }}.${{ PATCH }}-${{ GITHUB_SHA }}
