name: ci-app1

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/app1/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Get SemVer from file
        id: semver-reader
        uses: juliangruber/read-file-action@v1
        with:
          path: ./apps/app1/.version
          
      - name: Parse and Load SemVer
        run: |
          IFS='.'
          read -a semver <<< ${{ steps.semver-reader.outputs.content }}
          
          echo "${semver[0]}" >> $V_MAJOR # setting major semver version value 
          echo "${semver[1]}" >> $V_MINOR # setting minor semver version value
          echo "${semver[2]}" >> $V_PATCH # setting patch semver version value
          
          if [ -z "$V_MAJOR" ] || [ -z "$V_MINOR" ] || [ -z "$V_PATCH" ]; then # basic format check
              echo "Error: Invalid semver format."
              exit 1
          fi
      - 
        name: Build and push app1
        uses: docker/build-push-action@v3
        with:
          context: apps/app1/.
          push: true
          tags: markoklin/practice-repo:stage-v${{ MAJOR }}.${{ MINOR }}.${{ PATCH }}-${{ GITHUB_SHA }}
                #aandonov/app1:stage-v${{ MAJOR }}.${{ MINOR }}.${{ PATCH }}-${{ GITHUB_SHA }}
